name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue:
  google_fonts:
  oktoast:
  auto_size_text:
  email_validator:
  password_strength:
  font_awesome_flutter:
  flutter_svg:
  smooth_page_indicator:
  firebase_core:
  firebase_auth:
  google_sign_in:
  flutter_local_notifications:
  flutter_sms: ^2.3.2
  cloud_firestore: ^3.1.10
  firebase_database: ^9.0.8
  firebase_storage: ^10.2.9
  video_player: ^2.3.0
  share_plus:
  geolocator:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/svg/
